services:
  #
  # Ethereum mainnet geth
  #
  # https://hub.docker.com/r/ethereum/client-go
  # https://githwcat ub.com/Capgemini-AIE/ethereum-docker/blob/master/docker-compose-standalone.yml
  #

  # Primary Ethereum instance
  ethereum:
    image: ethereum/client-go:v1.10.26
    restart: unless-stopped
    container_name: ethereum
    command: >
      --sepolia
      --http
      --http.addr=0.0.0.0
      --http.corsdomain=*
      --http.vhosts=*
      --authrpc.jwtsecret=/jwtsecret
      --authrpc.port 8551
      --authrpc.addr=0.0.0.0
      --authrpc.vhosts=*
      --cache 8000
      --syncmode snap
    ports:
      - 30303:30303
      - 8545:8545
      - 8551:8551
    volumes:
      - ./data/ethereum:/root/.ethereum
      # ETH2 beacon chain node secret file for AuthRPC.
      # Share with your beacon client.
      # Generate this file: openssl rand -hex 32 > jwtsecret
      # and share to beacon chain node.
      - ./jwtsecret/jwtsecret:/jwtsecret

  # Beacon chain node using Lighthouse.
  # This node does not publicly expose any RPC servers
  # and only connects to above nodes using authrpc.
  lighthouse:
    container_name: lighthouse
    image: sigp/lighthouse
    restart: unless-stopped

    command: >
      lighthouse
      bn
       --network
       sepolia
       --http
       --http-address=0.0.0.0
       --http-port=5052
       --execution-endpoint=http://ethereum:8551
       --execution-jwt=/jwtsecret
       --checkpoint-sync-url=https://beaconstate-sepolia.chainsafe.io
       --disable-deposit-contract-sync
    ports:
      - 5052:5052
    environment:
      # Do a full backtrace when lighthouse crashes
      - RUST_BACKTRACE=full
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./jwtsecret/jwtsecret:/jwtsecret
